# Setup
title: Scope This
tagline: I was just thinking
url: https://scopethis.github.io/
paginate: 1
baseurl: https://scopethis.github.io/

permalink: pretty

markdown:         kramdown
highlighter:      rouge

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Simon  Hamilton
  url: https://twitter.com/mdo
  email: simon@scopethis.net

# Custom vars
version: 3.0.0
